### ISSUE TITLE
potential restructuring & establishing resources for imaging-based platforms

### ISSUE THREAD

**Issue by HelenaLC** [lmweber/OSTA#48]
Summarizing thoughts on spatial in R/Bioc that came up here or there during this week's Ascona workshop. More food for thought than specifics, but I'd be keen on putting aside some time to work on this (while keeping in touch with Estella or anyone else on board).

- Generally, it might be worth splitting into general intro, tech-specific chapters, advanced/multi-modal tasks, exemplary workflows. E.g., QC is very distinct for CosMx vs. Visium, deconvolution is specific to the latter etc.
- Early days were Visium-centric, but we have good representation across platforms in the community by now. The following come to mind (besides outstanding issues, and by no means complete)
  - brief tech background on imaging-based ST (e.g., some details on barcoding, negative/false codes, FOVs etc.)
  - QC on imaging-based ST (Risso et al. could pinch in here; I've also done some work here)
  - handling of molecules & polygons from *.parquet* (might become obsolete, but worth showcasing for now?)
  - point pattern analysis (ping Robinson & Patrick et al.)
  - anything sp/sf/spatstat really, as this might best emphasize “the native power of R” in some cases
  - basic neighborhood analyses (e.g., `RANN`) + niche stuff (`imcRtools`, `concordex`, ...)
  - CosMx example? (some intricacies compared to Xenium and friends)
  - besides `ExperimentHub`, collecting links to publicly available datasets across platforms could be useful for developers
  - besides pointers to other packages, adding references to independent benchmarks on specific tasks would be nice for users

Hoping that we make a coordinated push (soonish) to established some basic resources/pointers. Once general concepts are in place, anything new/missed could be added/elaborated without making claims on superiority of any one method at this point. Especially youngsters dealing with these data for the first time might quickly resort to other frameworks. I think there's a lot in R/Bioc, but it's harder to find than it could be, maybe... Let's change that as a (and for the) community :)!

**Comment by lmweber** [comment]
Thanks for these comments, yes I think this all sounds good. The earlier versions were definitely Visium-centric, and it makes sense to do some restructuring now regarding the newer single-cell resolution spatial platforms.

For the purposes of long-term maintenance, I think it will be good to try to keep the scope relatively narrow in a couple of ways -- specifically by continuing to focus only on commercially-available platforms (since these will tend to be by far the most widely used), and using only R packages that are on Bioconductor or CRAN within the code examples (which does exclude a large number of packages from GitHub, but GitHub packages make things very difficult for testing / building). And overall always trying to keep in mind the general principles / best practices for analyses that apply across platforms (for the steps where this makes sense, so e.g. clustering but not QC).

**Comment by HelenaLC** [comment]
this has been addressed.
